/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.sun.nio.sctp.MessageInfo;
import controlador.clsControlador;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author rene
 */
public class index extends javax.swing.JFrame implements ActionListener{
    private int[][] matriz;
     clsControlador atrControlador = null;
    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        btnSimular = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        lb_evoluciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lb_celulas = new javax.swing.JTextField();
        lb_iniciales = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jlb_regla = new javax.swing.JLabel();
        jtxt_regla = new javax.swing.JTextField();
        cbox_otro = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        cbox_juegodelavida = new javax.swing.JCheckBox();
        btn_guardar = new javax.swing.JButton();
        panel_Lienzo = new javax.swing.JPanel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSimular.setText("Aceptar");
        btnSimular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularActionPerformed(evt);
            }
        });

        jLabel2.setText("evoluciones");

        jLabel1.setText("celulas:");

        lb_celulas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_celulasActionPerformed(evt);
            }
        });

        lb_iniciales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lb_inicialesActionPerformed(evt);
            }
        });

        jLabel3.setText("valoresIniciales");

        jlb_regla.setText("regla");

        cbox_otro.setText("von-newmann");
        cbox_otro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_otroActionPerformed(evt);
            }
        });

        jButton1.setText("paso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbox_juegodelavida.setText("juego de la vida");
        cbox_juegodelavida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_juegodelavidaActionPerformed(evt);
            }
        });

        btn_guardar.setText("guardar");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cbox_otro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbox_juegodelavida)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_celulas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_evoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlb_regla)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtxt_regla, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lb_iniciales, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimular)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btn_guardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cbox_juegodelavida))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbox_otro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_celulas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lb_evoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_iniciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jlb_regla)
                    .addComponent(jtxt_regla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_guardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_LienzoLayout = new javax.swing.GroupLayout(panel_Lienzo);
        panel_Lienzo.setLayout(panel_LienzoLayout);
        panel_LienzoLayout.setHorizontalGroup(
            panel_LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel_LienzoLayout.setVerticalGroup(
            panel_LienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_Lienzo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_celulasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_celulasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_celulasActionPerformed
    private void crearMatriz(int parFila,int parColumnas){
        matriz = new int[parFila][parColumnas];
        for (int i = 0; i <parFila; i++) {
            for (int j = 0; j <parColumnas; j++) {
                matriz[i][j] = 0;
            }
        }
        
    }
    private void btnSimularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularActionPerformed
        if (this.cbox_otro.isSelected() || this.cbox_juegodelavida.isSelected())
        {
                int k =0;
                this.panel_Lienzo.removeAll();
                int varCelulas =Integer.parseInt(this.lb_celulas.getText());
                int varEvoluciones = Integer.parseInt(this.lb_evoluciones.getText());
                this.crearMatriz(varCelulas,varEvoluciones);
                this.iniciar(matriz, varCelulas,varEvoluciones );
                this.paintAll(this.getGraphics());
                    
               
        }else{    
                if (!validarCampos()){
                    this.panel_Lienzo.removeAll();
                    int varCelulas =Integer.parseInt(this.lb_celulas.getText());
                    int varEvoluciones = Integer.parseInt(this.lb_evoluciones.getText());
                    int varRegla = Integer.parseInt(this.jtxt_regla.getText());
                    ArrayList varColeccion = obtenerValoresIniciales();
                    clsControlador objControl = new clsControlador();
                    int[][] auxMatriz = objControl.iniciarAtomataCelular(varCelulas,varRegla,varEvoluciones,varColeccion);
                    this.iniciar(auxMatriz,varCelulas,varEvoluciones);
                    this.paintAll(this.getGraphics());
                }
        }
       
    }//GEN-LAST:event_btnSimularActionPerformed
    private boolean validarCampos(){
               boolean varResultado  = true;
                boolean boolRegla = this.jtxt_regla.getText().isEmpty();
                boolean boolCelulas =this.lb_celulas.getText().isEmpty();
                boolean boolEvolucion =this.lb_evoluciones.getText().isEmpty();
                boolean boolInicial =this.lb_iniciales.getText().isEmpty();
                    if (boolRegla || boolCelulas || boolEvolucion || boolInicial)
                    {
                         JOptionPane.showMessageDialog(null, "campos vacios", "adevetencia", JOptionPane.WARNING_MESSAGE);
                         
                    }
                    else{
                        varResultado = false;
                    }
                    
                    return varResultado;
    }
    
    private ArrayList obtenerValoresIniciales(){
        ArrayList varColeccion = new ArrayList();
        String[] tempCol = this.lb_iniciales.getText().split(",");
        for (int i = 0; i < tempCol.length; i++) {
            varColeccion.add(Integer.parseInt(tempCol[i]));
        }
        return varColeccion;
    }
     @Override
    public void actionPerformed(ActionEvent e) {
        clsCuadro objBoton = (clsCuadro)e.getSource(); //obtiene el objeto el cual se  le dio click
        objBoton.cambiarEstado();
        matriz[objBoton.getPosX()][objBoton.getPosY()] = objBoton.getEstado();
                
    }
    private void lb_inicialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lb_inicialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lb_inicialesActionPerformed

    private void cbox_otroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_otroActionPerformed
            if (this.cbox_otro.isSelected()) {
            
            this.lb_iniciales.setEnabled(false);
            this.jtxt_regla.setEnabled(false);
            this.cbox_juegodelavida.setSelected(false);
        }
            else{
            this.cbox_otro.setSelected(false);   
            this.lb_iniciales.setEnabled(true);
            this.jtxt_regla.setEnabled(true);
            }
    }//GEN-LAST:event_cbox_otroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.cbox_otro.isSelected()) {
            clsControlador objControlador = new clsControlador();
            matriz = objControlador.RealizarSimulacion(matriz);
            this.panel_Lienzo.removeAll();
            this.iniciar(matriz, matriz[0].length,matriz.length);
            this.paintAll(this.getGraphics());
        }
        if (this.cbox_juegodelavida.isSelected()) {
            clsControlador objControlador = new clsControlador();
            matriz = objControlador.RealizarSimulacionJuegoVida(matriz);
            this.panel_Lienzo.removeAll();
            this.iniciar(matriz, matriz[0].length,matriz.length);
            this.paintAll(this.getGraphics());
        }
           
        
        
        
      
                
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbox_juegodelavidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_juegodelavidaActionPerformed
         if (this.cbox_juegodelavida.isSelected()) {
            
            this.lb_iniciales.setEnabled(false);
            this.jtxt_regla.setEnabled(false);
        }
            else{
                
            this.lb_iniciales.setEnabled(true);
            this.jtxt_regla.setEnabled(true);
            }
    }//GEN-LAST:event_cbox_juegodelavidaActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        clsControlador control = new clsControlador();
        if (this.cbox_juegodelavida.isSelected()) {
            control.guardarAutomata(matriz,"juegoDelaVida.txt");
            JOptionPane.showMessageDialog(null, "Se guardo Correctamente", "juego de la vida", JOptionPane.INFORMATION_MESSAGE);
                         
        }
         if (this.cbox_otro.isSelected()) {
            control.guardarAutomata(matriz,"von-newmann.txt");
            JOptionPane.showMessageDialog(null, "Se guardo Correctamente", "von-nowmann", JOptionPane.INFORMATION_MESSAGE);
                         
        }
    }//GEN-LAST:event_btn_guardarActionPerformed
    private void iniciar(int[][] matriz,int varCelulas,int varEvoluciones){
        
        this.panel_Lienzo.setLayout(new java.awt.GridLayout(varEvoluciones,varCelulas));
        for (int i = 0; i < varEvoluciones; i++) {
            for (int j = 0; j <varCelulas; j++){
                 clsCuadro cuadro = new clsCuadro();
                 cuadro.setPosX(i);
                 cuadro.setPosY(j);
                 cuadro.addActionListener(this);//agreaga el evento al objeto boton: agrega metodo click
                if(matriz[i][j]==1){
                    cuadro.cambiarEstado();
                }
                cuadro.setVisible(true);
                panel_Lienzo.add(cuadro);
            }     
        }
       
       
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnSimular;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JCheckBox cbox_juegodelavida;
    private javax.swing.JCheckBox cbox_otro;
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlb_regla;
    private javax.swing.JTextField jtxt_regla;
    private javax.swing.JTextField lb_celulas;
    private javax.swing.JTextField lb_evoluciones;
    private javax.swing.JTextField lb_iniciales;
    private javax.swing.JPanel panel_Lienzo;
    // End of variables declaration//GEN-END:variables

   
}
